#!/bin/bash

REPO_DIR="/home/git/repositories/"
REPO_URL="$PWD"

if [ $(git rev-parse --is-bare-repository) = true ]
then
    REPO_NAME=${REPO_URL#$REPO_DIR}
    REPO_NAME=${REPO_NAME%.git}
else
    REPO_NAME=$(basename $(readlink -nf "$PWD"/..))
fi

if [ $REPO_NAME != 'gitolite-admin' ]; then
    curl -X POST -d "{ \"repository\": \"$REPO_NAME\" }" -H "Content-Type: application/json" --silent https://devhub.ewi.tudelft.nl/hooks/git-push
fi
